[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
[[redirects]]
  from = "/ecomm"
  to = "https://egghead.io/courses/create-an-ecommerce-store-with-next-js-and-stripe-checkout-562c?af=atzgap"
  status = 302
  force = true

[[redirects]]
  from = "/egghead-actions"
  to = "https://egghead.io/courses/create-a-new-github-action-to-automate-code-tasks-with-javascript-f1e9?af=atzgap"
  status = 302
  force = true

[[redirects]]
  from = "/cosmoshirt"
  to = "https://cottonbureau.com/products/cosmo-the-space-jellyfish#/5503032/tee-men-standard-tee-indigo-tri-blend-s"
  status = 302
  force = true

[[redirects]]
  from = "/hashnode-brand"
  to = "https://www.colbyfayock.com/hashnode-bootcamp-personal-brand"
  status = 302
  force = true


[[redirects]]
  from = "/wpnextjs"
  to = "https://github.com/colbyfayock/next-wordpress-starter"
  status = 302
  force = true
  
[[redirects]]
  from = "/frontendtestfest"
  to = "/front-end-test-fest"
  status = 302
  force = true

[[redirects]]
  from = "/reactvirtualconf"
  to = "/nextjs-wordpress-react-virtual-conf"
  status = 302
  force = true
  
[[redirects]]
  from = "/simplewebconf"
  to = "/simplewebconf-fundamentals"
  status = 302
  force = true
