[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

########
# Misc #
########

[[redirects]]
  from = "/cosmoshirt"
  to = "https://cottonbureau.com/products/cosmo-the-space-jellyfish#/5503032/tee-men-standard-tee-indigo-tri-blend-s"
  status = 302
  force = true

[[redirects]]
  from = "/ecomm"
  to = "https://egghead.io/courses/create-an-ecommerce-store-with-next-js-and-stripe-checkout-562c?af=atzgap"
  status = 302
  force = true

[[redirects]]
  from = "/egghead-actions"
  to = "https://egghead.io/courses/create-a-new-github-action-to-automate-code-tasks-with-javascript-f1e9?af=atzgap"
  status = 302
  force = true

[[redirects]]
  from = "/wpnextjs"
  to = "https://github.com/colbyfayock/next-wordpress-starter"
  status = 302
  force = true

################
# Amazon Links #
################

[[redirects]]
  from = "/adapters"
  to = "https://amzn.to/3hhXbYK"
  status = 302
  force = true

[[redirects]]
  from = "/clamps"
  to = "https://amzn.to/2ThkQjZ"
  status = 302
  force = true

[[redirects]]
  from = "/keylights"
  to = "https://amzn.to/2UbS5Wg"
  status = 302
  force = true

[[redirects]]
  from = "/monopod"
  to = "https://amzn.to/2UbUyA0"
  status = 302
  force = true

###############
# Conferences #
###############

[[redirects]]
  from = "/decoupleddays"
  to = "/decoupled-days-scaling-nextjs-with-wordpress"
  status = 302
  force = true

[[redirects]]
  from = "/frontendtestfest"
  to = "/front-end-test-fest"
  status = 302
  force = true

[[redirects]]
  from = "/hashnode-brand"
  to = "https://www.colbyfayock.com/hashnode-bootcamp-personal-brand"
  status = 302
  force = true

[[redirects]]
  from = "/reactvirtualconf"
  to = "/nextjs-wordpress-react-virtual-conf"
  status = 302
  force = true

[[redirects]]
  from = "/simplewebconf"
  to = "/simplewebconf-fundamentals"
  status = 302
  force = true

###############
# Event Notes #
###############

[[redirects]]
  from = "/3-hours-of-jamstack-2020"
  to = "/event-notes/3-hours-of-jamstack-2020"
  status = 301
  force = true

[[redirects]]
  from = "/accento-digital-2020"
  to = "/event-notes/accento-digital-2020"
  status = 301
  force = true

[[redirects]]
  from = "/applitools-storybook-webinar"
  to = "/event-notes/applitools-storybook-webinar"
  status = 301
  force = true

[[redirects]]
  from = "/byteconf-2020"
  to = "/event-notes/byteconf-2020"
  status = 301
  force = true

[[redirects]]
  from = "/click-deploy"
  to = "/event-notes/click-deploy"
  status = 301
  force = true

[[redirects]]
  from = "/cloudflare-tv-ecommerce"
  to = "/event-notes/cloudflare-tv-ecommerce"
  status = 301
  force = true

[[redirects]]
  from = "/conf42-2020"
  to = "/event-notes/conf42-2020"
  status = 301
  force = true

[[redirects]]
  from = "/decoupled-days-scaling-next-js-with-wordpress"
  to = "/event-notes/decoupled-days-scaling-next-js-with-wordpress"
  status = 301
  force = true

[[redirects]]
  from = "/developer-week-austin-2020"
  to = "/event-notes/developer-week-austin-2020"
  status = 301
  force = true

[[redirects]]
  from = "/egghead-talks-ecommerce"
  to = "/event-notes/egghead-talks-ecommerce"
  status = 301
  force = true

[[redirects]]
  from = "/egghead-talks-fundamentals-of-web-development"
  to = "/event-notes/egghead-talks-fundamentals-of-web-development"
  status = 301
  force = true

[[redirects]]
  from = "/forkwell-ecommerce"
  to = "/event-notes/forkwell-ecommerce"
  status = 301
  force = true

[[redirects]]
  from = "/forwardjs-2020"
  to = "/event-notes/forwardjs-2020"
  status = 301
  force = true

[[redirects]]
  from = "/front-end-test-fest"
  to = "/event-notes/front-end-test-fest"
  status = 301
  force = true

[[redirects]]
  from = "/frontconf2020"
  to = "/event-notes/frontconf-2020"
  status = 301
  force = true

[[redirects]]
  from = "/frontconf-2020"
  to = "/event-notes/frontconf-2020"
  status = 301
  force = true

[[redirects]]
  from = "/gatsby-days-reconfigured"
  to = "/event-notes/gatsby-days-reconfigured"
  status = 301
  force = true

[[redirects]]
  from = "/hashnode-bootcamp-personal-brand"
  to = "/event-notes/hashnode-bootcamp-personal-brand"
  status = 301
  force = true

[[redirects]]
  from = "/jamstack-conf-2020"
  to = "/event-notes/jamstack-conf-2020"
  status = 301
  force = true

[[redirects]]
  from = "/jnation-2020"
  to = "/event-notes/jnation-2020"
  status = 301
  force = true

[[redirects]]
  from = "/jsnation-fundamentals"
  to = "/event-notes/jsnation-fundamentals"
  status = 301
  force = true

[[redirects]]
  from = "/lbt-github-actions"
  to = "/event-notes/lbt-github-actions"
  status = 301
  force = true

[[redirects]]
  from = "/mdc-github-actions"
  to = "/event-notes/mdc-github-actions"
  status = 301
  force = true

[[redirects]]
  from = "/middlesbroughfe"
  to = "/event-notes/middlesbrough-fe"
  status = 301
  force = true

[[redirects]]
  from = "/middlesbrough-fe"
  to = "/event-notes/middlesbrough-fe"
  status = 301
  force = true

[[redirects]]
  from = "/next-js-wordpress-react-virtual-conf"
  to = "/event-notes/next-js-wordpress-react-virtual-conf"
  status = 301
  force = true

[[redirects]]
  from = "/react-festival-visual-testing"
  to = "/event-notes/react-festival-visual-testing"
  status = 301
  force = true

[[redirects]]
  from = "/react-global-2020"
  to = "/event-notes/react-global-2020"
  status = 301
  force = true

[[redirects]]
  from = "/react-summit-wordpress"
  to = "/event-notes/react-summit-wordpress"
  status = 301
  force = true

[[redirects]]
  from = "/react-virtual-conf-2020"
  to = "/event-notes/react-virtual-conf-2020"
  status = 301
  force = true

[[redirects]]
  from = "/simplewebconf-fundamentals"
  to = "/event-notes/simplewebconf-fundamentals"
  status = 301
  force = true

[[redirects]]
  from = "/snipcart-next-js"
  to = "/event-notes/snipcart-next-js"
  status = 301
  force = true

[[redirects]]
  from = "/the-jam-2021"
  to = "/event-notes/the-jam-2021"
  status = 301
  force = true

[[redirects]]
  from = "/thunderplains-2020"
  to = "/event-notes/thunderplains-2020"
  status = 301
  force = true

[[redirects]]
  from = "/wordcamp-philly-2020"
  to = "/event-notes/wordcamp-philly-2020"
  status = 301
  force = true

#########
# TALKS #
#########

[[redirects]]
  from = "/bringing-remote-sensing-and-disaster-relief-to-the-jamstack"
  to = "/talks/bringing-remote-sensing-and-disaster-relief-to-the-jamstack"
  status = 301
  force = true

[[redirects]]
  from = "/building-maps-with-impact-on-react-and-the-jamstack"
  to = "/talks/building-maps-with-impact-on-react-and-the-jamstack"
  status = 301
  force = true

[[redirects]]
  from = "/building-maps-with-impact-on-react-and-the-jamstack-frontconf"
  to = "/talks/bringing-remote-sensing-and-disaster-relief-to-the-jamstack"
  status = 301
  force = true

[[redirects]]
  from = "/mapping-gatsby-from-space"
  to = "/talks/mapping-gatsby-from-space"
  status = 301
  force = true

[[redirects]]
  from = "/supercharge-your-mapping-apps-with-gatsby-gatsby-days-reconfigured"
  to = "/talks/supercharge-your-mapping-apps-with-gatsby"
  status = 301
  force = true

############
# PODCASTS #
############

[[redirects]]
  from = "/codingcatdev-jamstack-handbook-with-colby-fayock"
  to = "/podcasts/codingcatdev-jamstack-handbook-with-colby-fayock"
  status = 301
  force = true

[[redirects]]
  from = "/jamstack-radio-jamstack-handbook-with-colby-fayock"
  to = "/podcasts/jamstack-radio-jamstack-handbook-with-colby-fayock"
  status = 301
  force = true

[[redirects]]
  from = "/react-round-up-put-down-the-javascript-learn-the-web-fundamentals-with-colby-fayock"
  to = "/podcasts/react-round-up-put-down-the-javascript-learn-the-web-fundamentals-with-colby-fayock"
  status = 301
  force = true

[[redirects]]
  from = "/thats-my-jamstack-on-mapping-like…-the-world-gatsby-science-and-more"
  to = "/podcasts/thats-my-jamstack-on-mapping-like…-the-world-gatsby-science-and-more"
  status = 301
  force = true