[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
[[redirects]]
  from = "/ecomm"
  to = "https://egghead.io/courses/create-an-ecommerce-store-with-next-js-and-stripe-checkout-562c?af=atzgap"
  status = 302
  force = true
