backend:
  name: github
  repo: colbyfayock/colbyfayock.com

media_folder: static/assets

collections:
  - name: blog
    label: Post
    folder: src/_posts
    create: true
    fields:
      - {
          name: "template",
          label: "Template",
          widget: "hidden",
          default: "blog-post"
        }
      - {
          name: title,
          label: Title
        }
      - {
          name: path,
          label: Path
        }
      - {
          name: date,
          label: Date,
          widget: date
        }
      - {
          name: categories,
          label: Categories
        }
      - {
          label: Body,
          name: body,
          widget: markdown
        }
  - name: page
    label: Page
    folder: src/_pages
    create: true
    fields:
      - {
          name: "template",
          label: "Template",
          widget: "hidden",
          default: "page"
        }
      - {
          name: title,
          label: Title
        }
      - {
          name: path,
          label: Path
        }
      - {
          label: Body,
          name: body,
          widget: markdown
        }