backend:
  name: github
  repo: colbyfayock/colbyfayock.com

publish_mode: editorial_workflow

media_folder: static/assets

collections:
  - name: post
    label: Post
    folder: src/_posts
    create: true
    fields:
      - {
          name: "template",
          label: "Template",
          widget: "hidden",
          default: "post"
        }
      - {
          name: title,
          label: Title
        }
      - {
          name: date,
          label: Date,
          widget: date
        }
      - {
          name: category,
          label: Category,
          widget: "select",
          options: - { label: "Coding", value: "coding" }
          - {
              label: "Graphic Design",
              value: "graphic-design"
            }
          - {
              label: "Photography",
              value: "photography"
            }
          - {
              label: "Theming",
              value: "theming"
            }
          - {
              label: "UI Design",
              value: "ui-design"
            }
          - {
              label: "Updates",
              value: "updates"
            }
          - {
              label: "Web Design",
              value: "web-design"
            }
        }
      - {
          label: Body,
          name: body,
          widget: markdown
        }
  - name: page
    label: Page
    folder: src/_pages
    create: true
    fields:
      - {
          name: "template",
          label: "Template",
          widget: "hidden",
          default: "page"
        }
      - {
          name: title,
          label: Title
        }
      - {
          name: path,
          label: Path
        }
      - {
          label: Body,
          name: body,
          widget: markdown
        }