backend:
  name: github
  repo: colbyfayock/colbyfayock.com

media_folder: static/assets

collections:
  - name: blog
    label: Post
    folder: src/_posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { label: Body, name: body, widget: markdown }